# Site settings
title: Mohsin Qureshi
SEOTitle: Moss Blog
header-img: img/bg_mountains.jpg
email: mohsinobaid@gmail.com
description: "Not Important"
keyword: "Moss, Mohsin, Qureshi, Machine Learning, Deep Learning, Software"
url: "https://mohsinobaid.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username: huxpro
# zhihu_username: huxpro
github_username: mohsinobaid
#twitter_username: huxpro
#facebook_username:  huxpro
linkedin_username:  mohsinqureshi #firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: hux

# Netease settings
# netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Mohsin Qureshi <br> Data Engineer"
sidebar-avatar: https://github.com/mohsinobaid.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Bhavesh ", href: "https://bhave.sh/" },
  ]
